### ISSUE TITLE
where is libsagui.so for rasbian ?

### ISSUE THREAD

**Issue by civilian7** [risoflora/brookframework#13]
can i download libsagui.so for rasberin?

**Comment by civilian7** [comment]
do you hav any plan for binary(arm 32 verfsion) distribute?

**Comment by silvioprog** [comment]
Hi @civilian7, thanks for opening the issue. A binary request was sent to https://github.com/risoflora/libsagui-docker/issues/2, so we will have binaries for ARM ASAP.

**Comment by silvioprog** [comment]
Hey @civilian7, ARM (64-bit only) support announced at Brook on Telegram:

https://t.me/brookframework

<img width="659" alt="Screenshot 2024-02-10 at 3 24 53 PM" src="https://github.com/risoflora/brookframework/assets/1456829/906bcce9-85ce-45e1-84bf-b4536cf4c8e1">

Brook running in Rasbian:

![WhatsApp Image 2024-02-10 at 1 22 29 PM](https://github.com/risoflora/brookframework/assets/1456829/d3e731db-5276-448b-ab92-2a3bc55b4d34)

We used an official image from [raspberrypi/software](https://www.raspberrypi.com/software).
