### ISSUE TITLE
can not compile using delphi tokyo 10.2

### ISSUE THREAD

**Issue by sirhanbaak** [risoflora/brookframework#14]
[dcc32 Error] BrookUtility.pas(55): E2003 Undeclared identifier: 'tkMRecord'
[dcc32 Error] BrookUtility.pas(56): E2026 Constant expression expected
[dcc32 Fatal Error] BrookHTTPCookies.pas(73): F2063 Could not compile used unit 'BrookUtility.pas'
Failed

**Comment by silvioprog** [comment]
Hi @sirhanbaak, thanks for reporting the issue.

Could you provide a small patch solving this problem? If so, you can fork the repository and send it as PR (Pull Request) to be merged to the trunk. :-)

Thank you!

**Comment by KaitoNakamura** [comment]
Hello the problem with tkMRecord is that it is commented out in version 10.2 and 10.2.3. ,
Here is the cutout from the unit :

  // Sync with compiler internals
  TTypeKind = (tkUnknown, tkInteger, tkChar, tkEnumeration, tkFloat,
    tkString, tkSet, tkClass, tkMethod, tkWChar, tkLString, tkWString,
    tkVariant, tkArray, tkRecord, tkInterface, tkInt64, tkDynArray, tkUString,
    tkClassRef, tkPointer, tkProcedure {, tkMRecord});
