### ISSUE TITLE
Dockerizing with Alpine Linux needs pseudo-tty allocation by '-it' option to 'docker run'

### ISSUE THREAD

**Issue by PierceNg** [risoflora/brookframework#16]
**Environment:**

- Host is Xubuntu 20.04
- FPC 3.2.0
- Lazarus 2.0.10
- libsagui is built from source cloned from the repo, master branch, last commit 67c1aae556b9bd86d3eb36a949ce98f944adc69f
- Brook is clone of this repo, master branch, last commit 77243829602fc80cbba138ff87fb8a6f7904aebe
- Program is Examples/Console/FPC/hellohttpsrv.lpr
- libsagui, Brook and the Hello program are built on Ubuntu host

```
% ls -l
total 1968
-rw-r--r-- 1 pierce pierce     307 Aug 15 08:33 Dockerfile
-rwxrwxr-x 1 pierce pierce 1104056 Aug 15 08:53 hellohttpsrv*
-rwxr-xr-x 1 pierce pierce  901816 Aug 15 00:32 libsagui.so.3*
```
Program works on command line:

```
% LD_LIBRARY_PATH=`pwd` ./hellohttpsrv
Server running at http://localhost:8080
```

In another terminal window:

```
% curl http://127.0.0.1:8080
<html><head><title>Hello world</title></head><body>Hello world</body></html>%    
```

Dockerfile:

```
% cat Dockerfile
FROM alpine:3.12
RUN apk --no-cache --update add libc6-compat
WORKDIR /app
COPY hellohttpsrv /app/helloworld
COPY libsagui.so.3 /lib/libsagui.so.3
RUN addgroup -g 1099 apprunner \
  && adduser -D -u 1099 -G apprunner -h /home/apprunner apprunner
USER apprunner:apprunner
EXPOSE 8080
CMD ["/app/helloworld"]

```

Build and tag as ```helloworld:brook4```:

```
% sudo docker build -t helloworld:brook4 .
...
Successfully tagged helloworld:brook4
```

The resulting Docker container exits immediately though:

```
% sudo docker run --rm -p 8080:8080 helloworld:brook4 
Server running at http://localhost:8080
% 
```

But running the Docker container interactively (by using ```-it``` option and running ```sh```) works:

```
% sudo docker run -it --rm -p 8080:8080 helloworld:brook4 sh
/app $ ls -l
total 1080
-rwxrwxr-x    1 root     root       1104056 Aug 15 00:53 helloworld
/app $ ./helloworld
Server running at http://localhost:8080
```

In another terminal window:

```
% curl http://127.0.0.1:8080            
<html><head><title>Hello world</title></head><body>Hello world</body></html>%
```

And running with ```-it``` option to ```docker run``` works too:

```
% sudo docker run -it --rm -p 8080:8080 helloworld:brook4
Server running at http://localhost:8080
```
In another terminal window:

```
% curl http://127.0.0.1:8080            
<html><head><title>Hello world</title></head><body>Hello world</body></html>%
```

Not sure if this counts as a bug; I've not encountered the need to use '-it' option when dockerizing other server-type programs.

Reference: [My posts to Lazarus forum](https://forum.lazarus.freepascal.org/index.php/topic,51034.0.html) that also talk about fcl-web and BrookFreePascal that have pure Pascal HTTP servers.

**Comment by silvioprog** [comment]
Hi @PierceNg, thanks for providing such full steps! I have never tried Sagui/Brook on Alpine before, so I'm very happy to see them working fine in such a minimal system. :-)

Regarding the problem you are getting, it seems not related to Brook. In general, to run a console application in a container in non interactive mode, the application needs to avoid to exit prematurely after getting executed, so maybe using something like [`TSimpleEvent.WaitFor(INFINITE)`](https://www.freepascal.org/docs-html/current/fcl/syncobjs/teventobject.waitfor.html) would help you to do that for any platform. For example, something [like this](https://github.com/risoflora/brookfreepascal/blob/master/brokers/Tardigrade/brooktardigradebroker.pas#L357).

Let me know if the information above helps you to solve the problem.

**Comment by PierceNg** [comment]
Hi @silvioprog. I came to Brook Framework after doing the same Alpine Docker thing with fcl-web and BrookFreePascal. Based on your reply I now realize I made some assumptions without reading the code. :-P Now that I know the example is literally a console program, I will be able to daemonize it.
