### ISSUE TITLE
Primitive kinds in BrookUtility (5.2.0) Compiler Version to low

### ISSUE THREAD

**Issue by KaitoNakamura** [risoflora/brookframework#18]
In Line 56 the Compiler Version is to low.
_"[tkClassRef..{$IF CompilerVersion >= 32.0}tkMRecord{$ELSE}tkProcedure{$ENDIF}]"_

You can fix it by change the Compiler Version to 33.0 . I have it with 10.2.1 tested and it works.

**Environment:**

OS, compiler and Brook version to reproduce the problem, e.g.:

- Windows
- Delphi 10.2.1
- Brook 5.2.0

**Comment by silvioprog** [comment]
@KaitoNakamura, thank you for reporting. It will be solved according you suggested.
