### ISSUE TITLE
dcc32 Fatal Error in BrookMathExpression.pas with D 10.2.1

### ISSUE THREAD

**Issue by KaitoNakamura** [risoflora/brookframework#19]
When you create the BrookFramework, you get a Fatal Error. ([dcc32 Fatal Error] BrookMathExpression.pas(492): F2084 Internal Error: C20339)
But the problem is in line 485 "FExtensionsHandle[FExtensions.Count] := Default(sg_expr_extension);"
If I Uncommenting this line, the project compiles. 
On the quick, however, I could not determine what problem he has here.

**Environment:**

OS, compiler and Brook version to reproduce the problem, e.g.:

- Windows
- Delphi 10.2.1
- Brook 5.1.x and 5.2.0
- Sagui 3.1.x x86_64 and 3.2.x

**Comment by silvioprog** [comment]
@KaitoNakamura, I have been trying to reproduce it, but it doesn't raise any errors. 😞 Could you provide the full steps or a minimal example to reproduce it? My steps were:

1. Open the example `brookframework\Examples\FMX\MathExpression_Example.dpr` and change its target from 32-bit to 64-bit;
2. Build, run it and click the button `Calculate now!`.

**Environment:**

- Windows 10
- Delphi 10.4 (Update 1)
- Brook 5.2
- Sagui 3.2 64-bit

**Comment by KaitoNakamura** [comment]
The error occurs already when compiling the package. So when you want to install the package.
I suspect that this is an internal problem of the compiler of the version 10.2.x. I can't test it with other versions at the moment. But had this already with the old Brook Framework version. Since I did not need this part, I only commented it out. 

I only added this error so that you know that there is a problem with one of the Delphi versions. Only Embarcadero can give an exact answer what is wrong, because the developers are the only ones who can do something with the number. You could contact support directly with the error message.

**Comment by silvioprog** [comment]
@KaitoNakamura, a new version was published to [GetIt](http://docwiki.embarcadero.com/RADStudio/Sydney/en/GetIt_Package_Manager_Window). Could you try to install using it?

**Comment by KaitoNakamura** [comment]
With GetIt I get the same error (F2084 Internal Error: C20339).

**Comment by silvioprog** [comment]
@KaitoNakamura, could you test the following change?:

```diff
-  FExtensionsHandle[FExtensions.Count] := Default(sg_expr_extension);
+  FillChar(FExtensionsHandle[FExtensions.Count], SizeOf(sg_expr_extension), #0);
```

i.e. using `FillChar` instead of `Default`.

**Comment by KaitoNakamura** [comment]
@silvioprog  Works very well. :-)
You can close this case. 
Thanks
