### ISSUE TITLE
Access Violation (C0000005)

### ISSUE THREAD

**Issue by KaitoNakamura** [risoflora/brookframework#20]
After calling the URL, the program stops with an access violation (C0000005) when calling against TBrookHTTPResponse.IsEmpty (sg_httpres_is_empty). 

**Steps to reproduce:**

use your own excemple Project and run the urlrouter.exe.
Use the given URL and Port and wait a sec. then the Application Crash with AV C0..05.

**Environment:**

OS, compiler and Brook version to reproduce the problem, e.g.:

- Windows
- Delphi 10.2.1
- Brook 5.2.0
- Sagui 3.2.0 x86_64

**Comment by silvioprog** [comment]
@KaitoNakamura, thanks for reporting! This is a serious bug and a new (fixed) version will be release quickly.
