### ISSUE TITLE
In BrookHTTPCookies in Line 278 "VEncoder.Destroy;" do not work under Linux

### ISSUE THREAD

**Issue by KaitoNakamura** [risoflora/brookframework#21]
In Windows the Compiler accept the line 278 "VEncoder.Destroy;" but not the Linux compiler.
you need to use Free or DisposeOf here.

[DCC Fehler] BrookHTTPCookies.pas(278): E2362 Auf protected-Symbol TObject.Destroy kann nicht zugegriffen werden

**Environment:**

OS, compiler and Brook version to reproduce the problem, e.g.:

- Linux
- Delphi 10.2.x
- Brook 5.4.1
- Sagui 3.3.0 x86_64

**Comment by silvioprog** [comment]
@KaitoNakamura thanks for reporting! Changed to `Free` as requested and committed in `5.4.4`.

**Comment by KaitoNakamura** [comment]
Hello @silvioprog ,

If you want to be backwards compatible and also support the ARC model, you should use DisposeOf instead of Free. DisposeOf automatically calls Free when not in ARC mode. When calling Free in ARC mode, nothing happens and you get memory leaks.
I forgot to mention that. Better you replace all Free calls with DisposeOf.

**Comment by silvioprog** [comment]
Hi @KaitoNakamura. The project must compile in FPC too, which doesn't provide a `DisposeOf()` method.

**Comment by KaitoNakamura** [comment]
As an idea use in addition {$IFNDEF AUTOREFCOUNT} DisposeOf {$ENDIF}
