### ISSUE TITLE
Support HTML multipart/form-data form submit

### ISSUE THREAD

**Issue by Beanv587** [risoflora/brookframework#22]
Hello

I am using Delphi 10.2 in the Examples of httpuploads. I tested it and found that it seemed to support only files, not text。。

For example, I added < input type = "text" name = "user" >, but I couldn't get the value of user in the DoRequest event.
![aa](https://user-images.githubusercontent.com/30143806/109917828-eb809580-7cf0-11eb-857f-61177df1ab13.png)

ARequest.Params seems that only supported forms with the application / x-www-form-urlencoded attribute。

How can I get the value of user?

Thank you

**Comment by silvioprog** [comment]
Hi @Beanv587.

Now the examples for uploading files [were updated](https://github.com/risoflora/brookframework/commit/d197aadb6397e6403f655d2ec76a1b375e33be35) for how to handle uploads and fields simultaneously, please take a look at them. 🙂

cheers

**Comment by Beanv587** [comment]
> Hi @Beanv587.
> 
> Now the examples for uploading files [were updated](https://github.com/risoflora/brookframework/commit/d197aadb6397e6403f655d2ec76a1b375e33be35) for how to handle uploads and fields simultaneously, please take a look at them. 🙂
> 
> cheers

@silvioprog 

OK,thank you very much
