### ISSUE TITLE
Headers ['Connection'] will be forced to be set to Keep-Alive.

### ISSUE THREAD

**Issue by Beanv587** [risoflora/brookframework#25]
Hi @silvioprog

Can you add an attribute to TBrookHTTPServer to decide whether to enable Keep-Alive. Currently, I try to modify AResponse.Headers ['Connection'], but it does not work. The Headers ['Connection'] will be forced to be set to Keep-Alive.

**Comment by silvioprog** [comment]
I'm not sure if I understood this requirement well. 🤔 Do you want some option to disable Keep-Alive? If so, you just need to put the header `Connection: close` on your client.

[By standard](https://datatracker.ietf.org/doc/html/rfc2616#section-8.1.2), the Keep-Alive connections must be enabled by default in HTTP/1.1:

> 8.1.2 Overall Operation
> 
>    A significant difference between HTTP/1.1 and earlier versions of
>    HTTP is that persistent connections are the default behavior of any
>    HTTP connection. That is, unless otherwise indicated, the client
>    SHOULD assume that the server will maintain a persistent connection,
>    even after error responses from the server.
