### ISSUE TITLE
Support for RAD / Delphi 11 (Alexandria)

### ISSUE THREAD

**Issue by KaitoNakamura** [risoflora/brookframework#36]
Hi,
I have seen that the Brook framework is no longer in the GitManager in Studio version 11.  After changing the filename Platform to BrookPlatform, I was able to install and work with Brook-Framework with RAD Studio 11. 

/Regards

**Environment:**

OS, compiler and Brook version to reproduce the problem, e.g.:

- Windows / Linux
- Delphi 11
- Brook 5.5.0

**Comment by silvioprog** [comment]
Hi @KaitoNakamura, thanks for reporting. I'll contact Embarcadero to check this problem.

**Comment by silvioprog** [comment]
Hi @KaitoNakamura, already reported to Embarcadero. Serge's answer referent to my question about to publish Brook in Delphi 11:

```
Hi Silvio,

Sure, I'll publish it.

Best regards, Serge.
```

I'm closing this issue because it will be solved by Embarcadero, but feel absolute free to reopen if you get any problem. :+1:
