### ISSUE TITLE
The router may not be thread safe. When router mode is used and Locker.Active=false, high concurrent requests will cause some AV. If you directly use the DoRequest method of TBrookHTTPServer, it will not cause AV.

### ISSUE THREAD

**Issue by leeonsoft** [risoflora/brookframework#38]
The router may not be thread safe. When router mode is used and Locker.Active=false, high concurrent requests will cause some AV. If you directly use the DoRequest method of TBrookHTTPServer, it will not cause AV.

**Comment by silvioprog** [comment]
Temporary branch to work on this bug: https://github.com/risoflora/brookframework/tree/thread-safe-router
