### ISSUE TITLE
Automatic integration with letsencrypt.org

### ISSUE THREAD

**Issue by silvioprog** [risoflora/brookframework#39]
It would be nice to create a component for integration with [letsencrypt.org](https://letsencrypt.org), allowing the Brook users to get the TLS certificates without external ACME clients like Certbot, LEGO etc.

**Comment by Al-Muhandis** [comment]
Perhaps it will be useful to someone. I add certificates through the certbot application. Example, at [this gist](https://gist.github.com/Al-Muhandis/fb965afc8032440d5894ae2e943c32f3)

**Comment by silvioprog** [comment]
Closing as not planned because we can use bots for automatic integration with LE. 🙌
