### ISSUE TITLE
Message and/or error suppression or callback function

### ISSUE THREAD

**Issue by vectorkovacspeter** [risoflora/brookframework#43]
Hello,

for better usability I think a feature to suppress libsagui messages and/or errors or forward them to a callback function would be very nice.

For example when the port is not free the libsagui dll shows error message, instead of raise some specific exception or call an OnError callback, or something can be handled by the caller application.

**Comment by silvioprog** [comment]
Hey @vectorkovacspeter, you mean something like this? [Source/BrookHTTPServer.pas#L312](https://github.com/risoflora/brookframework/blob/main/Source/BrookHTTPServer.pas#L312) 🙂

**Comment by vectorkovacspeter** [comment]
Thank man. I found this project also, and make some pilots with it, and also with mormot project, but finally use Indy with some modifications.

As I remember the performance tests for the http requests, mormot was the winner, but it was too complex for that particular job.

**Comment by silvioprog** [comment]
Alright, so let's close as solved. BTW feel free to reopen if you need something. 🙂
