### ISSUE TITLE
Wiki page from brookfreepascal should be transfered to brookframework project

### ISSUE THREAD

**Issue by DomenicoMammola** [risoflora/brookframework#45]
Hi,
the wiki page [How to configure TLS in Brook 5 Framework on a Microsoft Windows Server](https://github.com/risoflora/brookfreepascal/wiki/How-to-configure-TLS-in-Brook-5-Framework-on-a-Microsoft-Windows-Server) of the [brookfreepascal](https://github.com/risoflora/brookfreepascal) project should be transferred to the wiki of the  [brookframework](https://github.com/risoflora/brookframework) project as it is related to the TLS configuration of this latter project.
Thanks for your work!
Domenico

**Comment by silvioprog** [comment]
Hey @KevinLeeMorris, could you take care of this? 🙂

**Comment by KevinLeeMorris** [comment]
Done.

**Comment by silvioprog** [comment]
Thanks a lot man!
