### ISSUE TITLE
JChat for FireFox

### ISSUE THREAD

**Issue by KevinLeeMorris** [risoflora/brookframework#49]
A chat app meant to run on any browser. It's purpose is for internal "chat" type communication amongst members of a small team.   Although the obvious choice for this situation is Server Side Events, SSE has such severe limitations in both the server and the browser (6 instances), simple polling was used instead.  Brook 5 Framework is so efficient, handling thousands of unnecessary (as in "no new messages to send") polling events is easy. A JavaScript interval of 3 seconds is used to poll the server and get updates of which other users are active, inactive or idle, as well as a list of new conversations, or new messages.  Each conversation opens in it's own tab, and each message includes a face photo of the other user.  All HTML and Javascript is dead simple and from W3 Schools.  No libraries were used.

Interesting "Behind the scenes" Facts:

SSE Limitations:   [https://developer.mozilla.org/en-US/docs/Web/API/Server-sent_events/Using_server-sent_events](url)
About the name:  This app replaces a stand-alone windows executable chat app that was built in Delphi XE3 that was in use in our company for about 8 years prior. Having "For FireFox" helped users differentiate this app from the old Windows-only app.

Brook 5 Framework was the perfect fit for this situation.

**Comment by silvioprog** [comment]
Wow, thanks for the feedback @KevinLeeMorris, closing but keeping as Showcase.
