### ISSUE TITLE
Test project does not compile

### ISSUE THREAD

**Issue by AlexMikh33** [risoflora/brookframework#51]
The test project does not compile. Many errors.
Obviously, the test project has not been updated for a long time.

**Comment by silvioprog** [comment]
Hey @AlexMikh33, Delphi or Lazarus? (or both :sweat_smile:)

**Comment by silvioprog** [comment]
Also, pls feel totally free to send PR with fix. 🙂

**Comment by AlexMikh33** [comment]
> Hey @AlexMikh33, Delphi or Lazarus? (or both 😅)

Sorry, it looks like I posted in the wrong thread.
Problem with a Test app in your second Brook project - brookfreepascal 
https://github.com/risoflora/brookfreepascal
I was unable to compile it in Lazarus 3.0 (FPC 3.2.2) 
testbrookaction.pas (line 902): rt.AfterExecuteAction := @AfterExecuteAction;
_Error: Incompatible types: got "<procedure variable type of procedure(TObject;TBrookAction;TRequest;TResponse;TBrookRoute;var Boolean) of object;Register>" expected "<procedure variable type of procedure(TObject;TBrookAction;TRequest;TResponse;const TBrookArrayOfString;const TBrookArrayOfString;TBrookRoute;var Boolean) of object;Register>"_

And as I see this is not the only place.

**Comment by silvioprog** [comment]
Hey @Al-Muhandis, could you verify? 🙂

**Comment by Al-Muhandis** [comment]
We figured it out. This test is incomplete. We'd better delete it.

**Comment by Al-Muhandis** [comment]
We deleted the test folder because it was started, but did not receive a continuation (the framework itself works on work projects: everything is fine). Thanks for the feedback @AlexMikh33
