### ISSUE TITLE
win11, lazarus, brookframework, libsagui-3.dll with tls doesn't work?

### ISSUE THREAD

**Issue by yxh38658** [risoflora/brookframework#53]
I tried to build the demo project of brookframework/Examples/Console/FPC /hellohttpsrv.lpr with lazarus v3.0 on win11 and having libsagui-3.dll(tls_win_amd64 version) in the project folder.

An error happend with the message: libsagui-3.dll is not loaded. It happened in libsagui.pas, line 1014: GHandle := SafeLoadLibrary(AName); GHandle is 0 after calling the SafeLoadLibrary function.

I tried to put the libsagui-3.dll file in project folder and/or windows/system32. But I always got that error.

I then download libsagui-3.5.0-windows_amd64.zip and put the libsagui-3.dll without tls in the project folder. The program works!

Something wrong when load libsagui tls_win_amd64 version dll?

![image](https://github.com/risoflora/brookframework/assets/96913203/4a74d7cc-870d-4e68-a71b-75e7ea900f27)
![image](https://github.com/risoflora/brookframework/assets/96913203/2512b2d5-12c5-4812-a8e0-82ccee84bbc0)

**Comment by silvioprog** [comment]
Hey @yxh38658, to work with TLS support, you will need to download the DLLs from this [package](https://github.com/risoflora/libsagui/releases/download/v3.4.4/gnutls-3.8.3-mingw_amd64.zip)  and put alongside Sagui DLL.

**Comment by yxh38658** [comment]
It works! Thank you.
